### ISSUE TITLE
Move team and projects from Asana to GH

### ISSUE THREAD

**Issue by renatomcamilio** [CodersWithoutBordersTech/org#1]
- [x] CwB Main project
- [x] Refugee Lawyer
- [ ] Helping Hands? 
- [ ] Junior Dev Training Ground?

**Comment by renatomcamilio** [comment]
@abbeyjackson I think I've moved everything regarding CwB and Refugee Lawyer to this Project; Let me know if you need help on Helping Hand / Junior Dev [...];

**Comment by abbeyjackson** [comment]
All done!
